apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: intel-latency-single-node
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiImplementation: OpenMPI
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          # nodeName: thin002.hpc.rd.areasciencepark.it
          nodeName: kprod-00.kub.rd.areasciencepark.it
          containers:
          - image: pasianeight/intelbench:2021.3
            imagePullPolicy: IfNotPresent
            name: osu-launcher
            securityContext:
              runAsUser: 1000
            command:
            - mpirun
            args:
            - -n
            - "2"
            - /home/mpiuser/code/IMB-MPI1
            - pingpong
    Worker:
      replicas: 2
      template:
        metadata:
          labels:
            app: osu-worker
        spec:
          # nodeName: thin003.hpc.rd.areasciencepark.it
          nodeName: kprod-01.kub.rd.areasciencepark.it
          containers:
          - image: pasianeight/intelbench:2021.3
            imagePullPolicy: IfNotPresent
            name: osu-worker
            securityContext:
              runAsUser: 1000
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/mpiuser/.sshd_config
            readinessProbe:
              tcpSocket:
                port: 2222
              initialDelaySeconds: 2
          topologySpreadConstraints:
          - maxSkew: 2
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app: osu-worker


